### ISSUE TITLE
Add venue and map for DOC CPH16

### ISSUE THREAD

**Issue by monaslarsen** [CoDeConf/CoDeConf.github.io#19]
<img width="513" alt="doc cph 16 venue" src="https://cloud.githubusercontent.com/assets/13627068/12978526/b1d7180c-d0d1-11e5-98ff-208d91795c00.png">

**Comment by monaslarsen** [comment]
Dampfærgevej 10 
2100 København Ø

**Comment by monaslarsen** [comment]
https://goo.gl/maps/FUqFdXysJjM2

**Comment by monaslarsen** [comment]
How to get there:

Bus 26 going to Langelinjekaj. Stop: Indiakaj
(By the DFDS terminal)

**Comment by alexsedova** [comment]
closed by 7257bb608029b788c2b1e084c4eecebea38b60b6
