### ISSUE TITLE
I can see your DIV!

### ISSUE THREAD

**Issue by lakruzz** [CoDeConf/CoDeConf.github.io#2]
@meekrosoft 

at http://www.code-conf.com/day-of-docker-osl15/sponsors/

The div is showing:

![image](https://cloud.githubusercontent.com/assets/155492/10762868/1199dc4c-7cc8-11e5-862f-931551bc92e1.png)

**Comment by meekrosoft** [comment]
Fixed in commit 
https://github.com/CoDeConf/CoDeConf.github.io/commit/d88257c1cd356b633ef2606e25680523fd3128e4
