### ISSUE TITLE
Make the individual events stand out

### ISSUE THREAD

**Issue by lakruzz** [CoDeConf/CoDeConf.github.io#31]
The STHLM and CPH DoC events are true copies of the DOD Oslo event:

OSLO:
![image](https://cloud.githubusercontent.com/assets/155492/13145141/fc019880-d64e-11e5-8104-7df1e99e2ad4.png)

CPH
![image](https://cloud.githubusercontent.com/assets/155492/13145154/0d84b5d8-d64f-11e5-88db-395866c76ef8.png)

STHLM
![image](https://cloud.githubusercontent.com/assets/155492/13145158/162bc708-d64f-11e5-980e-6064853e647f.png)

The individual event need to stand out - copy and paste reuse is not very encouraging.
- [ ] Change front page pic on CPH
- [ ] Change front page pic on STHLM

**Comment by alexsedova** [comment]
closed by 82b56d39c84ab64a23f41c017247e23a3c719985
