### ISSUE TITLE
Sponsors CPH and STHLM

### ISSUE THREAD

**Issue by lakruzz** [CoDeConf/CoDeConf.github.io#32]
![image](https://cloud.githubusercontent.com/assets/155492/13145223/8fbe793a-d64f-11e5-8b79-f46a7389886b.png)
- [ ] Caption can only span one line
- [ ] The Delivery of Things logo should have should have transparent background
- [ ] There should be more margin at the bottom

Have a look at how it was orginally done: (paste is from the CoDe STHLM conf)
![image](https://cloud.githubusercontent.com/assets/155492/13145293/f691be60-d64f-11e5-8318-010c19c2382f.png)

We need to look (more) professional!

**Comment by lakruzz** [comment]
Same issues with Docker:
![image](https://cloud.githubusercontent.com/assets/155492/13145312/25da00f6-d650-11e5-92a5-3643df9cedf2.png)

**Comment by alexsedova** [comment]
@lakruzz check now pls. I fixed in issue28
