### ISSUE TITLE
Vision Document for CoDe conferences

### ISSUE THREAD

**Issue by lakruzz** [CoDeConf/CoDeConf.github.io#37]
The CoDe web is hosted at [www.code-conf.com](http://www.code-conf.com)

**code-conf.com shall be a portal of announcements of Continuous Delivery and DevOps related conferences, events, meetups, trainings and hackatons.**

The following features and abilities are desired:
### Layout
- It's shall support events in one of two formats: _one-page-announcements_ as well as _sub-sites_
- Each layout shall have support for sponsors
- Each event shall have support for integrated registration (both for Eventbrite and for meetups.com)
- Look-and-feel shall be recognizable across all sites
### Content and usability
- Content shall be given as either MarkDown, YAML or a combination hereof
- Each new page or sub-site shall have and automated setup based on a template (`rake`?)
- When a site or page is marked _archived_ I shall be obvious that it's a past event, and it shall be listed in the archive - SEO shall be maintained, even for archived events.
### Design and implementation
- Hosted at GitHub
- Sub-sites should potentially be individual  git repositories
- Design should be responsive, using _Bootstrap_
- All CSS should be build from either SCSS or SASS

**Comment by meekrosoft** [comment]
Would love to see some template generation scripts as a later feature.  Like rails scaffolding.

```
codeconf create --conference "CoDe:OSL 2016" --date 2016-04-14 --subdir "osl16"
codeconf create --meetup "Automation Nights 15.04" --date 2016-04-14 --url "http://www.meetup.com/Oslo-Embedded-Software-Meetup/events/226883233/"
codeconf create --training "Docker for Admin and Operations" --date 2016-04-14 --subdir "docker201604"
codeconf archive "docker201604"
```

etc

**Comment by illus0r** [comment]
@lakruzz 
I have a lot of questions :)
1. How do we earn? I need to understand the business model.
2. What's a business task this site solves?
3. How will you understand whether the project succeed or failed?  
4. When do you want to launch the website?
5. Who are users? How do they get onto the site?
6. What a purpose of making subsites?

**Comment by lakruzz** [comment]
@illus0r I replied this on slack.

**Comment by illus0r** [comment]
> Would love to see some template generation scripts

@meekrosoft this looks possible. We can use [jekyll **command** plugin to generate files from the command line](http://jonas.brusman.se/2012/12/28/create-jekyll-posts-from-the-command-line/)

```
thor jekyll:new The title of the new post
```

this code creates a post with frontmatter and proper name

**Comment by illus0r** [comment]
@lakruzz @meekrosoft and Jonathan, feel free to correct mistakes I made.

---

# Ivan's vision of the task and some ideas

We want to build a brand of **code-conf**: recognizable. We need this brand to rise the status of our events. 

For this purpose we want to invent a website. It's interface should help attenders to 
- find conferences they are interested in,
- provide all necessary information about these events,
- and make a payment process easy.

The interface should present sponsors as well. We want to make them look respectable. New sponsors should wish to be presented on the conference page.

## Appearance

Should be mobile friendly => designed according _mobile first_ approach.

Different events should be distinguishable but should look like of the same brand. We may want to make guidelined logos like [MIT did](https://vimeo.com/109891648) (see [more](http://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_mit_media_lab_by_pentagram.php)) or auto-generated logos [like MIT did before](https://vimeo.com/20250134).

## Structure

The structure of the conference may be complicated:
- description,
- tags-categories,
- dates-location-price,
- agenda,
- program,
- speakers,
- sponsors,
- social share buttons

So we need a way to present this info according to attenders's interests.

Old events should go into an archive (urls should be kept).

## Generator

We want to create this structure easily so we want to generate an `event` files from the `cli`. Site will reside on :octocat: github pages, but generation will run on local computers.

## Subscription

People are lazy to browse websites. At least me. I read _rss_ and _emails_ but it requires an afford to go to conferences list and select something to participate. 

I'd like to receive emails about ongoing events on interesting topics. Why not to make a **newsletter** form a significant part of the website?

It shouldn't be an universal form, I want to **filter** the spam I'll receive! Ideally — mark past or further conferences to keep notified about them. Or choose tags (categories?) i want to watch.

---

Competitors
- http://gotocon.com/archive
  - http://gotocon.com/stockholm-2016/
- http://oredev.org
